'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System


'This class was auto-generated by the StronglyTypedResourceBuilder
'class via a tool like ResGen or Visual Studio.
'To add or remove a member, edit your .ResX file then rerun ResGen
'with the /str option, or rebuild your VS project.
'''<summary>
'''  A strongly-typed resource class, for looking up localized strings, etc.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
 Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
 Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
Friend Class PrintRibbonControllerResources
    
    Private Shared resourceMan As Global.System.Resources.ResourceManager
    
    Private Shared resourceCulture As Global.System.Globalization.CultureInfo
    
    <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
    Friend Sub New()
        MyBase.New
    End Sub
    
    '''<summary>
    '''  Returns the cached ResourceManager instance used by this class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
        Get
            If Object.ReferenceEquals(resourceMan, Nothing) Then
                Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("sms.PrintRibbonControllerResources", GetType(PrintRibbonControllerResources).Assembly)
                resourceMan = temp
            End If
            Return resourceMan
        End Get
    End Property
    
    '''<summary>
    '''  Overrides the current thread's CurrentUICulture property for all
    '''  resource lookups using this strongly typed resource class.
    '''</summary>
    <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
        Get
            Return resourceCulture
        End Get
        Set
            resourceCulture = value
        End Set
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ClosePreview() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ClosePreview", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ClosePreviewLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ClosePreviewLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_Customize() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Customize", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_CustomizeLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_CustomizeLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_Document() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Document", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_DocumentMap() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_DocumentMap", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_DocumentMapLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_DocumentMapLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_EditPageHF() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_EditPageHF", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_EditPageHFLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_EditPageHFLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportCsv() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportCsv", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportCsvLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportCsvLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportFile() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportFile", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportFileLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportFileLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportGraphic() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportGraphic", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportGraphicLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportGraphicLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportHtm() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportHtm", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportHtmLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportHtmLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportMht() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportMht", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportMhtLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportMhtLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportPdf() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportPdf", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportPdfLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportPdfLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportRtf() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportRtf", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportRtfLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportRtfLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportTxt() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportTxt", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportTxtLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportTxtLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportXls() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportXls", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ExportXlsLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ExportXlsLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_FillBackground() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_FillBackground", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_FillBackgroundLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_FillBackgroundLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_Find() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Find", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_FindLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_FindLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_HandTool() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_HandTool", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_Magnifier() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Magnifier", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_MultiplePages() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_MultiplePages", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_MultiplePagesLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_MultiplePagesLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_Open() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Open", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_OpenLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_OpenLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_PageMargins() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageMargins", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageMarginsLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsModerate() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageMarginsModerate", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsNarrow() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageMarginsNarrow", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsNormal() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageMarginsNormal", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_PageMarginsWide() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageMarginsWide", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_PageOrientation() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageOrientation", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_PageOrientationLandscape() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageOrientationLandscape", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_PageOrientationLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageOrientationLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_PageOrientationPortrait() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageOrientationPortrait", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_PageSetupDialog() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PageSetupDialog", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_A3() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A3", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_A4() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A4", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_A5() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A5", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_A6() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_A6", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_Executive() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Executive", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_Legal() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Legal", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_Letter() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Letter", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_PaperKind_Tabloid() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PaperKind_Tabloid", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_PaperSize() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PaperSize", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_PaperSizeLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PaperSizeLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_Parameters() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Parameters", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ParametersLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ParametersLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_Pointer() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Pointer", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_Print() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Print", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_PrintDirect() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PrintDirect", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_PrintDirectLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PrintDirectLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_PrintLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PrintLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_PrintSetup() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PrintSetup", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_PrintSetupLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_PrintSetupLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_Save() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Save", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_SaveLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SaveLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_Scale() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Scale", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ScaleLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ScaleLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_SendCsv() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendCsv", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_SendCsvLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendCsvLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_SendFile() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendFile", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_SendFileLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendFileLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_SendGraphic() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendGraphic", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_SendGraphicLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendGraphicLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_SendMht() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendMht", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_SendMhtLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendMhtLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_SendPdf() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendPdf", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_SendPdfLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendPdfLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_SendRtf() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendRtf", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_SendRtfLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendRtfLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_SendTxt() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendTxt", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_SendTxtLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendTxtLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_SendXls() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendXls", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_SendXlsLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_SendXlsLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ShowFirstPage() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ShowFirstPage", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ShowFirstPageLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ShowFirstPageLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ShowLastPage() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ShowLastPage", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ShowLastPageLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ShowLastPageLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ShowNextPage() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ShowNextPage", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ShowNextPageLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ShowNextPageLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ShowPrevPage() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ShowPrevPage", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ShowPrevPageLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ShowPrevPageLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_Watermark() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Watermark", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_WatermarkLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_WatermarkLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_Zoom() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_Zoom", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ZoomIn() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ZoomIn", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ZoomInLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ZoomInLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ZoomLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ZoomLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ZoomOut() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ZoomOut", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
    
    Friend Shared ReadOnly Property RibbonPrintPreview_ZoomOutLarge() As System.Drawing.Bitmap
        Get
            Dim obj As Object = ResourceManager.GetObject("RibbonPrintPreview_ZoomOutLarge", resourceCulture)
            Return CType(obj,System.Drawing.Bitmap)
        End Get
    End Property
End Class
